[package]
name = "garde"
version = "0.10.0"
edition = "2021"
repository = "https://github.com/jprochazk/garde"
license = "MIT OR Apache-2.0"
description = "Validation library"
keywords = ["validation", "validate", "valid"]
readme = "../README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = [
    "derive",
    "serde",
    "url",
    "credit-card",
    "phone-number",
    "email",
    "email-idna",
    "pattern",
]
serde = ["dep:serde"]
derive = ["dep:garde_derive"]
url = ["dep:url"]
credit-card = ["dep:card-validate"]
phone-number = ["dep:phonenumber"]
email = ["dep:regex", "dep:once_cell"]
email-idna = ["dep:idna"]
pattern = ["dep:regex", "dep:once_cell", "garde_derive?/regex"]
nightly-error-messages = []

[dependencies]
garde_derive = { version = "0.10.0", path = "../garde_derive", optional = true, default-features = false }

serde = { workspace = true, features = ["derive"], optional = true }
url = { workspace = true, optional = true }
card-validate = { workspace = true, optional = true }
phonenumber = { workspace = true, optional = true }
regex = { workspace = true, optional = true }
once_cell = { workspace = true, optional = true }
idna = { workspace = true, optional = true }
