[package]
name = "garde_derive_tests"
version = "0.0.0"
edition = "2021"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dev-dependencies]
garde = { version = "0.2", path = "../garde" }
trybuild = { verison = "1.0" }
